### ISSUE TITLE
Any plan for automatic updates of TTRSS?

### ISSUE THREAD

**Issue by Kwbmm** [nVentiveUX/docker-ttrss#2]
I'm wondering if there's any plan for automatic TTRSS update. I see that commits are being pushed constantly to update to the latest upstream commit.
I haven't tested, but I'm sure that you can retrieve the latest commit id.
I don't know, though, if this can be done in docker file configuration.

**Comment by bigbrozer** [comment]
This is a good idea ! :-)
I did not pay attention but this is possible to specify a branch name (let say **master**) instead of a commit hash at upstream level:

```
https://git.tt-rss.org/fox/tt-rss/archive/master.tar.gz
```

Then, I can use a [cron job in Travis CI](https://docs.travis-ci.com/user/cron-jobs/) to build regularly a new image.

Let me think about it...
