### ISSUE TITLE
Add support for GlobalConfig

### ISSUE THREAD

**Issue by Kwbmm** [nVentiveUX/docker-ttrss#5]
Hello, the newest build is broken

I believe [this](https://community.tt-rss.org/t/rip-config-php-hello-classes-config-php/4337) may be the cause of the problem.

The complete error I get on the newest docker build is the following:

```
ttrss         | Database connection succeeded.
ttrss         | Some tt-rss data already exists in this database. Skipping initialization.
ttrss         | <pre>Exception while creating PDO object:SQLSTATE[08006] [7] fe_sendauth: no password supplied</pre>Database connection succeeded.
```

**Comment by bigbrozer** [comment]
Thanks for pointing this out ! I will work on the old config migration. It was a missing feature I have attempted to work on in this image but if the upstream project will support config through env vars this is awesome :-)

**Comment by bigbrozer** [comment]
@Kwbmm, I have prepared needed changes in a development image that you can use to test `nventiveux/ttrss:develop`. Would it be possible to perform some tests using this new image?

For information, the changes are located in branch `features/config-migration-putenv`.

Many thanks in advance.

**Comment by Kwbmm** [comment]
I can, but I'm running your images on a Raspberry Pi 3, so I would need the arm32v6 image. Would it be possible to push that image rather than the amd64? Or even better, why not pushing both?

(main reason why I've been using your images is because you're the only one I found packaging in a sensible way TTRSS for raspberries and keeping it up to date :sweat_smile: )

**Comment by bigbrozer** [comment]
Thanks for your comment ! Glad to hear it is useful ;-)

I had several stuff left behind like switching from Travis CI to GitHub Actions. This is now done and that will drastically simplify the image releasing process. Still need to adjust one or two things but it looks good, at least for **develop** :smile:.

You can use image tagged as [nventiveux/ttrss-arm32v6:develop-2021.03.09](https://hub.docker.com/repository/docker/nventiveux/ttrss-arm32v6/tags?page=1&ordering=last_updated) for testing.

**Comment by Kwbmm** [comment]
Thanks!
I'll switch over to TTRSS this weekend and test it out for the following week!

**Comment by Kwbmm** [comment]
So I ended up pulling `nventiveux/ttrss-arm32v6:latest`. Looks good, except for the `E_NOTICE` logs I get in the Preferences:

```
Undefined index: timestamp
1. include/functions.php(483): ttrss_error_handler(8, Undefined index: timestamp, include/functions.php, 483, [{"git_commit":null,"git_timestamp":null,"last_error":null,"ttrss_version":{"version":"UNKNOWN (Unsupported)"}})
2. prefs.php(152): get_version(, , )

Real IP: 192.168.1.1
Forwarded For: 192.168.1.1
Forwarded Protocol: https
Remote IP: 172.23.0.2
Request URI: /prefs.php?tab=system
User agent: Mozilla/5.0 (X11; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0

Undefined index: commit
1. include/functions.php(482): ttrss_error_handler(8, Undefined index: commit, include/functions.php, 482, [{"git_commit":null,"git_timestamp":null,"last_error":null,"ttrss_version":{"version":"UNKNOWN (Unsupported)"}})
2. prefs.php(152): get_version(, , )

Real IP: 192.168.1.1
Forwarded For: 192.168.1.1
Forwarded Protocol: https
Remote IP: 172.23.0.2
Request URI: /prefs.php?tab=system
User agent: Mozilla/5.0 (X11; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0
```

**Comment by bigbrozer** [comment]
Thanks for the feedbacks. Would you please switch to tag **master** instead of ~latest~ ? Unfortunately the tag **latest** was sibling the old **master** (prior to #7) which is a cron job running each saturday :sob: from the old CI. Things are clean now, sorry for the mess...

Personally, I have switched to this new tag my TTRSS installation and it works well (mobile app too) apart some NOTICE / WARNINGS in php code... Apparently, PHP8 support is quite new for this project and not all part of the code have been upgraded (this is not harmful but you will notice it in logs).

Now you have more option if you prefer to control the upgrade (still need to document that in the README):

* Use **master** tag for latest stable releases (based on latest code of TTRSS)
* Use **develop** branch for testing new features related to the image. Things can break a lot here :smile:.
* Use any of the above and append the date of the build (eg. `master-2021.03.13`) to stick to a release and control when you want to upgrade. Look here to know all the available tags for [x86_64](https://hub.docker.com/r/nventiveux/ttrss/tags?page=1&ordering=last_updated) / [arm32v6](https://hub.docker.com/r/nventiveux/ttrss-arm32v6/tags?page=1&ordering=last_updated) images.

**Comment by Kwbmm** [comment]
Nice! And if `master` tag is stable, what is `stable` tag? :sweat_smile:

**Comment by bigbrozer** [comment]
You got me ! That one is also something from the past. I have removed the stable tag too to avoid confusion. The cron setup to auto refresh the image based on latest upstream code is in place, see #9 for extra details.
